from _typeshed import Incomplete

from plexapi.base import PlexObject

class Settings(PlexObject):
    key: str
    def __init__(self, server, data, initpath: Incomplete | None = None) -> None: ...
    def __getattr__(self, attr): ...
    def __setattr__(self, attr, value): ...
    def all(self): ...
    def get(self, id): ...
    def groups(self): ...
    def group(self, group): ...
    def save(self) -> None: ...

class Setting(PlexObject):
    TYPES: Incomplete
    def set(self, value) -> None: ...
    def toUrl(self): ...

class Preferences(Setting):
    TAG: str
    FILTER: str
