services:
  plexanibridge:
    image: ghcr.io/eliasbenb/plexanibridge:v0 # :vX, :vX.Y, :vX.Y.Z, :main, :develop, :latest
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Etc/UTC
      ANILIST_TOKEN: eyJ...
      PLEX_TOKEN: 2Sb...
      PLEX_USER: username
      PLEX_URL: http://plex:32400
      # PLEX_SECTIONS: '[]'
      # PLEX_GENRES: '[]'
      # PLEX_METADATA_SOURCE: local
      # SYNC_INTERVAL: 3600
      # POLLING_SCAN: False
      # FULL_SCAN: False
      # DESTRUCTIVE_SYNC: False
      # EXCLUDED_SYNC_FIELDS: '["notes", "score"]'
      # DRY_RUN: False
      # LOG_LEVEL: INFO
      # BATCH_REQUESTS: False
      # SEARCH_FALLBACK_THRESHOLD=-1
      # DATA_PATH: ./data
    volumes:
      - /path/to/plexanibridge/data:/config
    restart: unless-stopped
