services:
  plexanibridge:
    image: ghcr.io/eliasbenb/plexanibridge:latest
    environment:
      ANILIST_TOKEN: eyJ...
      PLEX_TOKEN: 2Sb...
      PLEX_USER: username
      PLEX_URL: http://plex:32400
      PLEX_SECTIONS: '["Anime", "Anime Movies"]'
      # SYNC_INTERVAL: 3600
      # PARTIAL_SCAN: True
      # DESTRUCTIVE_SYNC: False
      # EXCLUDED_SYNC_FIELDS: ["notes", "score"]
      # DATA_PATH: ./data
      # DRY_RUN: False
      # LOG_LEVEL: INFO
      # FUZZY_SEARCH_THRESHOLD: 90
    volumes:
      - ./data:/app/data
      # - ./logs:/app/logs
    restart: unless-stopped
