services:
  plexanibridge:
    image: ghcr.io/eliasbenb/plexanibridge:main
    environment:
      # SYNC_INTERVAL: 3600 # Time in seconds between each sync
      # PARTIAL_SCAN: True # Set to False to scan all Plex items, regardless of if it has already been processed by previous runs
      # DESTRUCTIVE_SYNC: False # Set to True to destructively sync Plex progress, ratings, adn notes with AniList. E.g. if ratings already exist in AniList but not in Plex, they will be removed from AniList.
      ANILIST_TOKEN: eyJ0eXALOiJKV1DiLCJFbGciOiJSUzI...
      ANILIST_USER: username
      PLEX_URL: http://localhost:32400
      PLEX_TOKEN: 2Sb... # https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/
      PLEX_SECTIONS: '["Anime", "Anime Movies"]'
      PLEX_USER: username
      # DB_PATH: db/plexanibridge.db
      # DRY_RUN: False # Use this to test the script without making any permanent changes
      # LOG_LEVEL: INFO # [DEBUG, INFO, WARNING, ERROR, CRITICAL]
      # FUZZY_SEARCH_THRESHOLD: 90 # [0-100] sets the strictness when matching anime title search results
    volumes:
      - ./db:/app/db
      # - ./logs:/app/logs
    restart: unless-stopped
