"""Basic authentication middleware."""

import secrets
from collections.abc import Callable

from fastapi.security import HTTPBasic
from starlette.exceptions import HTTPException
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import Response

from src import log

__all__ = ["BasicAuthMiddleware"]


class BasicAuthMiddleware(BaseHTTPMiddleware):
    """Middleware to enforce HTTP Basic Authentication."""

    def __init__(self, app, username: str, password: str, realm: str) -> None:
        """Initialize the BasicAuthMiddleware."""
        super().__init__(app)
        self.username = username
        self.password = password
        self.realm = realm
        self.security = HTTPBasic()

    async def dispatch(self, request: Request, call_next: Callable) -> Response:
        """Process the incoming request and enforce basic authentication.

        Args:
            request (Request): The incoming HTTP request.
            call_next (Callable): Function to call the next middleware or endpoint.

        Returns:
            Response: The HTTP response generated by the endpoint.
        """
        try:
            credentials = await self.security(request)
        except HTTPException:
            return self._challenge_response()

        if not credentials:
            return self._challenge_response()

        username_match = secrets.compare_digest(credentials.username, self.username)
        password_match = secrets.compare_digest(credentials.password, self.password)

        if not (username_match and password_match):
            return self._challenge_response()

        response = await call_next(request)
        return response

    def _challenge_response(self) -> Response:
        """Return a 401 response with the proper WWW-Authenticate header."""
        log.debug("Authentication failed, sending challenge response")
        return Response(
            status_code=401,
            headers={"WWW-Authenticate": f'Basic realm="{self.realm}"'},
        )
