"""Init

Revision ID: 6e710e6677c0
Revises: 
Create Date: 2024-12-21 11:56:14.628540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e710e6677c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animap',
    sa.Column('anidb_id', sa.Integer(), nullable=False),
    sa.Column('anilist_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('mal_id', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('tmdb_movie_id', sa.Integer(), nullable=True),
    sa.Column('tmdb_show_id', sa.Integer(), nullable=True),
    sa.Column('tvdb_id', sa.Integer(), nullable=True),
    sa.Column('tvdb_epoffset', sa.Integer(), nullable=True),
    sa.Column('tvdb_season', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('anidb_id')
    )
    op.create_index(op.f('ix_animap_anilist_id'), 'animap', ['anilist_id'], unique=False)
    op.create_index(op.f('ix_animap_imdb_id'), 'animap', ['imdb_id'], unique=False)
    op.create_index(op.f('ix_animap_mal_id'), 'animap', ['mal_id'], unique=False)
    op.create_index(op.f('ix_animap_tmdb_movie_id'), 'animap', ['tmdb_movie_id'], unique=False)
    op.create_index(op.f('ix_animap_tmdb_show_id'), 'animap', ['tmdb_show_id'], unique=False)
    op.create_index(op.f('ix_animap_tvdb_id'), 'animap', ['tvdb_id'], unique=False)
    op.create_table('house_keeping',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('house_keeping')
    op.drop_index(op.f('ix_animap_tvdb_id'), table_name='animap')
    op.drop_index(op.f('ix_animap_tmdb_show_id'), table_name='animap')
    op.drop_index(op.f('ix_animap_tmdb_movie_id'), table_name='animap')
    op.drop_index(op.f('ix_animap_mal_id'), table_name='animap')
    op.drop_index(op.f('ix_animap_imdb_id'), table_name='animap')
    op.drop_index(op.f('ix_animap_anilist_id'), table_name='animap')
    op.drop_table('animap')
    # ### end Alembic commands ###
