"""Initial revision

Revision ID: 77574a748435
Revises: 
Create Date: 2025-11-23 04:20:43.663382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77574a748435'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animap',
    sa.Column('anilist_id', sa.Integer(), nullable=False),
    sa.Column('anidb_id', sa.Integer(), nullable=True),
    sa.Column('imdb_id', sa.JSON(), nullable=True),
    sa.Column('mal_id', sa.JSON(), nullable=True),
    sa.Column('tmdb_movie_id', sa.JSON(), nullable=True),
    sa.Column('tmdb_show_id', sa.Integer(), nullable=True),
    sa.Column('tvdb_id', sa.Integer(), nullable=True),
    sa.Column('tmdb_mappings', sa.JSON(), nullable=True),
    sa.Column('tvdb_mappings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('anilist_id')
    )
    with op.batch_alter_table('animap', schema=None) as batch_op:
        batch_op.create_index('idx_imdb_tmdb', ['imdb_id', 'tmdb_movie_id'], unique=False)
        batch_op.create_index('idx_tmdb_season', ['tmdb_show_id', 'tmdb_mappings'], unique=False)
        batch_op.create_index('idx_tvdb_season', ['tvdb_id', 'tvdb_mappings'], unique=False)
        batch_op.create_index(batch_op.f('ix_animap_imdb_id'), ['imdb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animap_tmdb_mappings'), ['tmdb_mappings'], unique=False)
        batch_op.create_index(batch_op.f('ix_animap_tmdb_movie_id'), ['tmdb_movie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animap_tmdb_show_id'), ['tmdb_show_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animap_tvdb_id'), ['tvdb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animap_tvdb_mappings'), ['tvdb_mappings'], unique=False)

    op.create_table('house_keeping',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('pin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('list_namespace', sa.String(), nullable=False),
    sa.Column('list_media_key', sa.String(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pin_list_media_key'), ['list_media_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_pin_list_namespace'), ['list_namespace'], unique=False)
        batch_op.create_index('ix_pin_profile_list_keys', ['profile_name', 'list_namespace', 'list_media_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_pin_profile_name'), ['profile_name'], unique=False)

    op.create_table('sync_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('library_namespace', sa.String(), nullable=False),
    sa.Column('library_section_key', sa.String(), nullable=False),
    sa.Column('library_media_key', sa.String(), nullable=False),
    sa.Column('list_namespace', sa.String(), nullable=False),
    sa.Column('list_media_key', sa.String(), nullable=True),
    sa.Column('media_kind', sa.Enum('MOVIE', 'SHOW', 'SEASON', 'EPISODE', name='mediakind'), nullable=False),
    sa.Column('outcome', sa.Enum('SYNCED', 'SKIPPED', 'FAILED', 'NOT_FOUND', 'DELETED', 'PENDING', 'UNDONE', name='syncoutcome'), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_history_library_media_key'), ['library_media_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_history_library_namespace'), ['library_namespace'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_history_library_section_key'), ['library_section_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_history_list_media_key'), ['list_media_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_history_list_namespace'), ['list_namespace'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_history_media_kind'), ['media_kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_history_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_history_profile_name'), ['profile_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_history_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index('ix_sync_history_upsert_keys', ['profile_name', 'library_namespace', 'library_section_key', 'library_media_key', 'list_namespace', 'list_media_key', 'outcome'], unique=False)

    op.create_table('animap_provenance',
    sa.Column('anilist_id', sa.Integer(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['anilist_id'], ['animap.anilist_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('anilist_id', 'n')
    )
    with op.batch_alter_table('animap_provenance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animap_provenance_anilist_id'), ['anilist_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animap_provenance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animap_provenance_anilist_id'))

    op.drop_table('animap_provenance')
    with op.batch_alter_table('sync_history', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_history_upsert_keys')
        batch_op.drop_index(batch_op.f('ix_sync_history_timestamp'))
        batch_op.drop_index(batch_op.f('ix_sync_history_profile_name'))
        batch_op.drop_index(batch_op.f('ix_sync_history_outcome'))
        batch_op.drop_index(batch_op.f('ix_sync_history_media_kind'))
        batch_op.drop_index(batch_op.f('ix_sync_history_list_namespace'))
        batch_op.drop_index(batch_op.f('ix_sync_history_list_media_key'))
        batch_op.drop_index(batch_op.f('ix_sync_history_library_section_key'))
        batch_op.drop_index(batch_op.f('ix_sync_history_library_namespace'))
        batch_op.drop_index(batch_op.f('ix_sync_history_library_media_key'))

    op.drop_table('sync_history')
    with op.batch_alter_table('pin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pin_profile_name'))
        batch_op.drop_index('ix_pin_profile_list_keys')
        batch_op.drop_index(batch_op.f('ix_pin_list_namespace'))
        batch_op.drop_index(batch_op.f('ix_pin_list_media_key'))

    op.drop_table('pin')
    op.drop_table('house_keeping')
    with op.batch_alter_table('animap', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animap_tvdb_mappings'))
        batch_op.drop_index(batch_op.f('ix_animap_tvdb_id'))
        batch_op.drop_index(batch_op.f('ix_animap_tmdb_show_id'))
        batch_op.drop_index(batch_op.f('ix_animap_tmdb_movie_id'))
        batch_op.drop_index(batch_op.f('ix_animap_tmdb_mappings'))
        batch_op.drop_index(batch_op.f('ix_animap_imdb_id'))
        batch_op.drop_index('idx_tvdb_season')
        batch_op.drop_index('idx_tmdb_season')
        batch_op.drop_index('idx_imdb_tmdb')

    op.drop_table('animap')
    # ### end Alembic commands ###
