"""Add composite mapping indexes

Revision ID: 08f39c25b391
Revises: e89ead9178d7
Create Date: 2025-06-26 05:56:19.495133

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '08f39c25b391'
down_revision: Union[str, None] = 'e89ead9178d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animap', schema=None) as batch_op:
        batch_op.create_index('idx_imdb_tmdb', ['imdb_id', 'tmdb_movie_id'], unique=False)
        batch_op.create_index('idx_tvdb_season', ['tvdb_id', 'tvdb_mappings'], unique=False)
        batch_op.create_index(batch_op.f('ix_animap_tvdb_mappings'), ['tvdb_mappings'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animap', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animap_tvdb_mappings'))
        batch_op.drop_index('idx_tvdb_season')
        batch_op.drop_index('idx_imdb_tmdb')

    # ### end Alembic commands ###
