"""Added a sync failures table

Revision ID: 6fb5989efce6
Revises: e89ead9178d7
Create Date: 2025-05-04 00:03:27.546550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = '6fb5989efce6'
down_revision: Union[str, None] = 'e89ead9178d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failure',
    sa.Column('anilist_account_id', sa.Integer(), nullable=False),
    sa.Column('plex_account_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('rating_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('failed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('anilist_account_id', 'plex_account_id', 'section_id', 'rating_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failure')
    # ### end Alembic commands ###
