"""pin table

Revision ID: db24057a61c9
Revises: 12add4c4ffa9
Create Date: 2025-10-08 19:00:30.934679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db24057a61c9'
down_revision: Union[str, None] = '12add4c4ffa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('anilist_id', sa.Integer(), nullable=False),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pin_anilist_id'), ['anilist_id'], unique=False)
        batch_op.create_index('ix_pin_profile_anilist', ['profile_name', 'anilist_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_pin_profile_name'), ['profile_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pin_profile_name'))
        batch_op.drop_index('ix_pin_profile_anilist')
        batch_op.drop_index(batch_op.f('ix_pin_anilist_id'))

    op.drop_table('pin')
    # ### end Alembic commands ###
