"""Added provenance tracking table

Revision ID: 8387b3fd8a6a
Revises: 213f9be1534f
Create Date: 2025-09-19 00:29:08.882127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8387b3fd8a6a'
down_revision: Union[str, None] = '213f9be1534f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animap_provenance',
    sa.Column('anilist_id', sa.Integer(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['anilist_id'], ['animap.anilist_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('anilist_id', 'n')
    )
    with op.batch_alter_table('animap_provenance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animap_provenance_anilist_id'), ['anilist_id'], unique=False)

    # ### end Alembic commands ###

    op.execute("DELETE FROM animap")
    op.execute("DELETE FROM house_keeping WHERE key = 'animap_mappings_hash'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animap_provenance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animap_provenance_anilist_id'))

    op.drop_table('animap_provenance')
    # ### end Alembic commands ###
