"""Sync history table

Revision ID: cd371e53adcb
Revises: 08f39c25b391
Create Date: 2025-08-08 05:10:15.509159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd371e53adcb'
down_revision: Union[str, None] = '08f39c25b391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_name', sa.String(), nullable=False),
    sa.Column('plex_guid', sa.String(), nullable=True),
    sa.Column('plex_rating_key', sa.String(), nullable=False),
    sa.Column('plex_child_rating_key', sa.String(), nullable=True),
    sa.Column('plex_type', sa.Enum('MOVIE', 'SHOW', 'SEASON', 'EPISODE', name='mediatype'), nullable=False),
    sa.Column('anilist_id', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Enum('SYNCED', 'SKIPPED', 'FAILED', 'NOT_FOUND', 'DELETED', 'PENDING', name='syncoutcome'), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_history_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_history_plex_guid'), ['plex_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_history_plex_type'), ['plex_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_history_profile_name'), ['profile_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_history_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_history_timestamp'))
        batch_op.drop_index(batch_op.f('ix_sync_history_profile_name'))
        batch_op.drop_index(batch_op.f('ix_sync_history_plex_type'))
        batch_op.drop_index(batch_op.f('ix_sync_history_plex_guid'))
        batch_op.drop_index(batch_op.f('ix_sync_history_outcome'))

    op.drop_table('sync_history')
    # ### end Alembic commands ###
