"""sync_history composite indexes

Revision ID: 213f9be1534f
Revises: cd371e53adcb
Create Date: 2025-08-12 06:30:14.506677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '213f9be1534f'
down_revision: Union[str, None] = 'cd371e53adcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_history', schema=None) as batch_op:
        batch_op.create_index('ix_sync_history_upsert_keys', ['profile_name', 'plex_rating_key', 'plex_child_rating_key', 'plex_type', 'outcome'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_history', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_history_upsert_keys')

    # ### end Alembic commands ###
