"""Convert TVDB mappings to a dict

Revision ID: 6b471e97e780
Revises: c5581ec025a7
Create Date: 2025-02-17 20:24:50.010412

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # added

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b471e97e780"
down_revision: Union[str, None] = "c5581ec025a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM animap")
    op.execute("DELETE FROM house_keeping WHERE key = 'animap_cdn_hash'")
    op.execute("DELETE FROM house_keeping WHERE key = 'animap_custom_hash'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
