"""tmdb_mappings column

Revision ID: 12add4c4ffa9
Revises: 8387b3fd8a6a
Create Date: 2025-09-30 04:03:04.619505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12add4c4ffa9'
down_revision: Union[str, None] = '8387b3fd8a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tmdb_mappings', sa.JSON(), nullable=True))
        batch_op.create_index('idx_tmdb_season', ['tmdb_show_id', 'tmdb_mappings'], unique=False)
        batch_op.create_index(batch_op.f('ix_animap_tmdb_mappings'), ['tmdb_mappings'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animap', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animap_tmdb_mappings'))
        batch_op.drop_index('idx_tmdb_season')
        batch_op.drop_column('tmdb_mappings')

    # ### end Alembic commands ###
