"""scalar tmdb_show_id

Revision ID: 90496c989bdd
Revises: db24057a61c9
Create Date: 2025-10-20 10:41:57.362134

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '90496c989bdd'
down_revision: Union[str, None] = 'db24057a61c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animap', schema=None) as batch_op:
        batch_op.alter_column('tmdb_show_id',
               existing_type=sqlite.JSON(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animap', schema=None) as batch_op:
        batch_op.alter_column('tmdb_show_id',
               existing_type=sa.Integer(),
               type_=sqlite.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
